#!/bin/sh
#Author Piolo Martin
#Version 1.0

MY_WALLET="47AvjyMkQy6JFXQo7NDJ6QXaCawzc637jdcAG6BJUBofV8mGiPg2uKqhwFeuTm7UBo3dDBEaAd9w2EynVBsE6s615FqmDhK"
MY_WALLET_PASS="Dreyannz"
CPU_USAGE="75"

# DON'T EDIT BELOW THIS LINE
ALGO="cryptonight"
POOL_URL_AND_PORT="pool.supportxmr.com:80"
IP=$(ip route get 8.8.8.8| grep src| sed 's/.*src \(.*\)$/\1/g')
CONFIG_NAME="config.json"

#install libraries
add-apt-repository -y ppa:jonathonf/gcc-7.1
apt-get update
apt-get install -y libmicrohttpd-dev

# Install xmrig binary
cd /tmp
wget http://mymonero.s3-ap-southeast-1.amazonaws.com/xmrig.tar.bz2 -O xmrig.tar.bz2
tar -vxjf xmrig.tar.bz2
cp -f xmrig /usr/local/bin/xmrig
chmod +x /usr/local/bin/xmrig
rm -f xmrig.tar.bz2
rm xmrig

cd /etc
wget http://mymonero.s3-ap-southeast-1.amazonaws.com/config.v1.json -O ${CONFIG_NAME}
sed -i "s/ALGO/${ALGO}/g" ${CONFIG_NAME}
sed -i "s/POOL_URL_AND_PORT/${POOL_URL_AND_PORT}/g" ${CONFIG_NAME}
sed -i "s/WALLET_ADDRESS/${MY_WALLET}/g" ${CONFIG_NAME}
sed -i "s/WALLET_PASS/${MY_WALLET_PASS}-${IP}/g" ${CONFIG_NAME}
sed -i "s/CPU_USAGE/${CPU_USAGE}/g" ${CONFIG_NAME}

/usr/local/bin/xmrig -c /etc/config.json

# Insert to startup script
sed -i -e '$i \/usr/local/bin/xmrig -c /etc/config.json\n' /etc/rc.local
